import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    include: ['src/**/*.spec.ts'],
    exclude: ['src/database/seed.spec.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'text-summary'],
      thresholds: {
        lines: 5,
        functions: 20,
        branches: 30,
        statements: 5,
      },
      include: ['src/**/*.ts'],
      exclude: [
        'dist/**',
        'src/**/*.module.ts',
        'src/**/*.dto.ts',
        'src/**/*.entity.ts',
        'src/database/schema/**',
        'src/database/seed.ts',
        'src/database/seed.spec.ts',
        'src/main.ts',
        'src/common/decorators/**',
        'src/queue/processors/**',
        'src/**/dto/**',
        'src/auth/auth.controller.ts',
        'src/categories/categories.controller.ts',
        'src/products/products.controller.ts',
        'src/orders/orders.controller.ts',
        'src/payments/payments.controller.ts',
        'src/reviews/reviews.controller.ts',
        'src/shipping/shipping.controller.ts',
        'src/returns/returns.controller.ts',
        'src/search/search.controller.ts',
        'src/analytics/analytics.controller.ts',
        'src/chat/chat.controller.ts',
        'src/notifications/notifications.controller.ts',
        'src/inventory/inventory.controller.ts',
        'src/reputation/reputation.controller.ts',
        'src/disputes/disputes.controller.ts',
        'src/coupons/coupons.controller.ts',
        'src/banners/banners.controller.ts',
        'src/wishlists/wishlists.controller.ts',
        'src/vendors/vendors.controller.ts',
        'src/reports/reports.controller.ts',
        'src/storage/storage.controller.ts',
        'src/commissions/commissions.controller.ts',
        'src/payouts/payouts.controller.ts',
        'src/cart/cart.controller.ts',
        'src/cart/cart.service.ts',
        'src/commissions/commissions.service.ts',
        'src/payouts/payouts.service.ts',
        'src/coupons/coupons.service.ts',
        'src/wishlists/wishlists.service.ts',
        'src/banners/banners.service.ts',
        'src/storage/storage.service.ts',
        'src/vendors/vendors.service.ts',
        'src/reports/reports.service.ts',
        'src/reputation/reputation.service.ts',
        'src/disputes/disputes.service.ts',
        'src/inventory/inventory.service.ts',
      ],
    },
  },
});
